'use strict';

/* *
 * We create a language strings object containing all of our strings.
 * The keys for each string will then be referenced in our code, e.g. i18n.t('WELCOME_MSG').
 * The localisation interceptor in index.js will automatically choose the strings
 * that match the request's locale.
 * */

module.exports = {
  es: {
    translation: {
      SKILL_NAME: 'Curiosidades del Ajolote',
      WELCOME_MSG: '<emphasis level="strong">¡Hola {{name}}!</emphasis>Gracias por usar Curiosidades del Ajolote, para comenzar puedes decir: dime un dato curioso del ajolote... o si deseas detenerme solo di: ¡Cancela!... entonces, ¿cómo te puedo ayudar?',
      HELLO_MSG_WITHOUT_SSML: '¡Hola {{name}}! Gracias por usar a Curiosidades del Ajolote, para comenzar puedes decir: dime un dato curioso del ajolote... o si deseas detenerme solo di: ¡Cancela!... entonces, ¿cómo te puedo ayudar?',
      HELLO_MSG: '¡Hola Mundo!',
      HELP_MSG: 'Hola {{userName}}, veo que estas en {{location}} y tienes una temperatura de {{temperature}}. He visto que tienes una cafeteria a {{cafeteria}}. Te vamos a enviar un mail a {{email}}. Recuerda que puedes decir: dame un dato curioso del ajolote... o simplemente para detenerme puedes decir: ¡Cancela!... ¿Cómo te puedo ayudar?',
      GOODBYE_MSG: '<amazon:emotion name="excited" intensity="medium"> Hasta luego, y recuerda el ajolote se encuentra en peligro de extinción. </amazon:emotion>',
      REFLECTOR_MSG: 'Acabas de activar {{intentName}}',
      FALLBACK_MSG: 'Lo siento, no se nada sobre eso. Por favor inténtalo otra vez.',
      ERROR_MSG: '<audio src="soundbank://soundlibrary/musical/amzn_sfx_buzzer_small_01"/> Lo siento, ha habido un error. Por favor inténtalo otra vez.',

      GET_FACT_MESSAGE: 'Un dato curioso es que ',
      GET_TYPE_AXOLOTL: 'Has seleccionado el tipo de ajolote ',
      OK_COMPLETED_AXOLOTL: '<audio src="soundbank://soundlibrary/office/amzn_sfx_elevator_open_bell_01"/> <amazon:emotion name="excited" intensity="medium"> ¡Ese ajolote es el mejor del mundo!</amazon:emotion>',
      CONTACT_MESSAGE: 'Puedes obtener mas informacion en ajolote arroba alexa.com',
      NO_NAME_MSG: 'No se como te llamas, ¿Como debo dirigirme a ti?',
      NAME_SAVED_OK: 'Información guardada correctamente!',
      NAME_SAVING: 'Estoy guardando la información!',
      NO_ADDRESS_MSG: 'Este dispositivo no tiene configurada ninguna dirección. Te recomendamos usar un dispositivo físico o la app de Amazon Alexa',
      REQUEST_ADDRESS_MSG: 'Necesitamos acceder a su ubicación para continuar con la Skill.',
      HINT_TEXT_MSG: 'Intenta, \"Alexa, cuentame sobre el ajolote.\"',
      AVAILABLE_PRODUCTS_MSG: 'Los productos disponibles para la compra son:',
      AVAILABLE_PRODUCTS_REPROMPT_MSG: '¿Tienes alguna duda sobre los productos?',
      NOT_AVAILABLE_PRODUCTS_MSG: 'Lo siento pero no encuentro ningun producto disponible',
      UPSELL_MSG: 'Genial! Quieres saber mas sobre el producto?',
      BUY_SUCCESS_MSG: 'Compra realizada con éxito!',
      BUY_PURCHASED_MSG: 'Ya tienes la subscripción!',
      BUY_DENIED_MSG: 'Se ha denegado la compra a la subcripción!',
      BUY_ERROR_MSG: 'Ha habido un problema durante el proceso de compra, vuelva a intentarlo',
      REFUND_SUCCESS_MSG: 'Se ha procesado la devolución correctamente',
      REFUND_DENIED_MSG: 'Se ha denegado la devolución del producto',
      REFUND_NOT_PRODUCT_MSG: 'Este producto no lo tenias comprado',
      ACCOUNT_LINKING_NOT_DONE_MSG: 'Debes registrarte con tu usuario de Amazon. Te he nviado más informacion a tu app de Alexa',
      REMINDER_MSG: 'Este recordatorio es para hacerte saber que el ajolote se encuentra en peligro de extinción.',
      REMINDER_CREATED_SUCCESS: '¡Ha programado con éxito un recordatorio para saber más sobre los Ajolotes!',
      REMINDER_PERMISSIONS:'Por favor habilite los permisos de recordatorios en la aplicación de Amazon Alexa.',
      REMINDER_SCHEDULED: '¡Recuerda que los ajolotes estan en peligro de extinción!',
      REMINDER_CREATED_FAILURE: '¡Error al crear el recordatorio!',
      TIMER_FINISH: 'Temporizador del ajolote!!.',
      TIMER_PERMISSIONS:'Curiosidades del Ajolote necesita permiso para acceder a los temporizadores.',
      TIMER_ASK_CONFIG_PERMISSIONS:'¿Te gustaría configurar un temporizador?',
      TIMER_SORRY_CONFIG_PERMISSIONS:'Disculpa, no escuché tu respuesta, Curiosidades del Ajolote requiere tu permiso.',
      TIMER_ACCEPTED: 'Ahora que tenemos tu permiso para configurar un temporizador. ¿Te gustaría comenzar?',
      TIMER_NOT_ACCEPTED: 'Sin permisos, no puedo configurar un temporizador. Así que supongo que esto un adiós.',
      TIMER_CREATED_SUCCESS: '¡Ha programado con éxito un temporizador',
      TIMER_CREATED_ERROR: 'Hubo un error creando el timer',
      TIMER_NOT_STARTED: 'Esta bien, no iniciaré un temporizador.'
    },
  },
  en: {
    translation: {
      SKILL_NAME: 'Curiosities of the Axolotl',
      WELCOME_MSG: '<emphasis level="strong">Hello {{name}} !</emphasis>  welcome to Curiosities of the Axolotl, to start you can say: tell me a curious fact about the axolotl ... or if you want to stop me just say: Cancel! ... then how can I help you?',
      HELLO_MSG_WITHOUT_SSML: 'Hello {{name}}!  welcome to Curiosities of the Axolotl, to start you can say: tell me a curious fact about the axolotl ... or if you want to stop me just say: Cancel! ... then how can I help you?',
      HELLO_MSG: 'Hello World!',
      HELP_MSG: 'Hello {{userName}}, I am seeing that you are at {{location}} and you have a temperature of {{temperature}}. I have seen you have a cafeteria about {{cafeteria}}. We will sent you an email to {{email}} You can say: give me a curious fact about the axolotl ... or simply to stop me you can say: Cancel! ... How can I help you?',
      GOODBYE_MSG: '<amazon:emotion name="excited" intensity="medium">Goodbye, and remember the axolotl is in danger of extinction. </amazon:emotion>',
      REFLECTOR_MSG: 'You just activated {{intentName}}',
      FALLBACK_MSG: 'Sorry, I do not know anything about that. Please try again.',
      ERROR_MSG: '<audio src="soundbank://soundlibrary/musical/amzn_sfx_buzzer_small_01"/> Sorry, there was an error. Please try again.',

      GET_FACT_MESSAGE: 'A curious fact is that ',
      GET_TYPE_AXOLOTL: 'You have selected the type of axolotl ',
      OK_COMPLETED_AXOLOTL: '<audio src="soundbank://soundlibrary/office/amzn_sfx_elevator_open_bell_01"/> <amazon:emotion name="excited" intensity="medium"> That axolotl is the best in the world!</amazon:emotion>',
      CONTACT_MESSAGE: 'You can get more information on ajolote at alexa.com',
      NO_NAME_MSG: 'I do not know your know, ¿What is your name?',
      NAME_SAVED_OK: 'Information saved succefully!',
      NAME_SAVING: 'I am saving the information!',
      NO_ADDRESS_MSG: 'This device has no set any address configured. We recommend you to use a device or the Amazon Alexa app',
      REQUEST_ADDRESS_MSG: 'We need to acces to your address in order to continue.',
      HINT_TEXT_MSG: 'Try, \"Alexa, tell me something about Axolotl.\"',
      AVAILABLE_PRODUCTS_MSG: 'The available products are: ',
      AVAILABLE_PRODUCTS_REPROMPT_MSG: 'Do you have any questions about the products?',
      NOT_AVAILABLE_PRODUCTS_MSG: 'Sorry but I can\'t find any available products',
      UPSELL_MSG: 'Great! Do you want to know more about the product?',
      BUY_SUCCESS_MSG: 'Successful purchase!',
      BUY_PURCHASED_MSG: 'You already have the subscription!',
      BUY_DENIED_MSG: 'Subscription purchase denied!',
      BUY_ERROR_MSG: 'There was a problem during the purchase process, please try again',
      REFUND_SUCCESS_MSG: 'The refund has been processed successfully',
      REFUND_DENIED_MSG: 'Refund has been denied',
      REFUND_NOT_PRODUCT_MSG: 'You did not buy this product before',
      ACCOUNT_LINKING_NOT_DONE_MSG: 'You must register with your Amazon username. I have sent you more information to your Alexa app',
      REMINDER_MSG: 'This reminder is to let you know that the axolotl is in danger of extinction.',
      REMINDER_CREATED_SUCCESS: 'You have successfully scheduled a reminder to learn more about the Axolotls!',
      REMINDER_PERMISSIONS:'Please enable the reminder permissions in the Amazon Alexa App.',
      REMINDER_SCHEDULED: 'Remember that axolotls are in danger of extinction!',
      REMINDER_CREATED_FAILURE: 'There was an error creating the reminder!',
      TIMER_FINISH: 'Axolotel\'s timer.',
      TIMER_PERMISSIONS:'Curiosities of the Axolotl need your permission to access the timers.',
      TIMER_ASK_CONFIG_PERMISSIONS:'Would you like to set a timer?',
      TIMER_SORRY_CONFIG_PERMISSIONS:'Sorry, I did not hear your response, Curiosities of the Axolotl requires your permission.',
      TIMER_ACCEPTED: 'Now that we have your permission to set a timer. Would you like to start?',
      TIMER_NOT_ACCEPTED: 'Without permissions, I cannot set a timer. So I guess this is goodbye.', 
      TIMER_CREATED_SUCCESS: 'You have successfully set a timer',
      TIMER_CREATED_ERROR: 'There was an error creating the timer',
      TIMER_NOT_STARTED: 'Okay, I won\'t start a timer.'
    },
  },
};